site_name: GameApp Docs
site_url: https://welcome-club.vercel.app/

theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  plugins:
    - social

  extra:
    social:
      - icon: fontawesome/brands/github-alt
        link: https://github.com/james-willett
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/TheJamesWillett
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/willettjames/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list

copyright: |
  &copy; 2024 <a href="https://welcome-club.vercel.app/"  target="_blank" rel="noopener">GameApp</a>

#markdown_extensions:
#  - attr_list
#  - md_in_html
#  - pymdownx.superfences
#  - md_in_html
#  - abbr
#  - pymdownx.snippets

  
